robot_base_frame: $(arg prefix)base_footprint
transform_tolerance: 0.4
update_frequency: 5.0
publish_frequency: 1.0
obstacle_range: 3.0

footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

raytrace_range: 3.0
#mark_threshold: 1
publish_voxel_map: true
footprint_padding: 0.0
navigation_map:
  map_topic: /map

static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /$(arg prefix)magni/scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.55

virtual_walls_map:
  map_topic: /virtual_walls/map
  use_maximum: true
